[package]
version = "0.1.3"
name = "darwin-push-port-live-feed"
description = "Client to receive updates from the National Rail Darwin Push Port Live Feed."
homepage = "https://github.com/viral32111/darwin-push-port-live-feed"
documentation = "https://viral32111.github.io/darwin-push-port-live-feed/darwin-push-port-live-feed"
authors = [ "viral32111 <contact@viral32111.com>" ]
readme = "README.md"
license = "AGPL-3.0-only"
keywords = [ "microservice", "national-rail", "british-transport" ]
categories = [ "command-line-utilities", "database", "caching", "network-programming", "data-structures" ]
include = [ "src", "README.md", "LICENSE.txt" ]
publish = false
edition = "2021"
rust-version = "1.77"

[dependencies]
dotenvy = "0.15.7"
envy = "0.4.2"
serde = { version = "1.0.228", features = ["derive"] }
comfy-table = "7.2.2"
tokio = { version = "1.52.3", features = ["full"] }
anyhow = "1.0.103"
fastrand = "2.4.1"
gethostname = "1.1.0"
sha2 = "0.10.9"
futures = "0.3.32"
flate2 = "1.1.9"
quick-xml = "0.39.4"
uuid = { version = "1.20.0", features = ["v4"] }
