name: rabbitmq

services:
  rabbitmq:
    hostname: example
    image: rabbitmq:3.13-management
    pull_policy: always
    environment:
      - RABBITMQ_DEFAULT_USER=
      - RABBITMQ_DEFAULT_PASS=
    ports:
      - target: 5672
        published: 5672
        host_ip: 127.0.0.1
        protocol: tcp

      # Management (External)
      - target: 8080
        published: 8080
        host_ip: 127.0.0.1
        protocol: tcp

      # Management (Internal)
      - target: 15672
        published: 15672
        host_ip: 127.0.0.1
        protocol: tcp

      # Prometheus
      - target: 15692
        published: 15692
        host_ip: 127.0.0.1
        protocol: tcp
